### ISSUE TITLE
Adapt wg-resolve to work together with wg-netns

### ISSUE THREAD

**Issue by dadevel** [dadevel/wg-netns#18]
Spin-off from #12.

**Comment by dadevel** [comment]
@marek22k I pushed a new version of [wg-resolve](https://github.com/dadevel/wg-netns/blob/main/extras/wg-resolve/wg-resolve.sh).

**Comment by marek22k** [comment]
However, the script cannot resolve IPv6 for the destination.

**Comment by dadevel** [comment]
Sry, forgot about that. I'll replace `dig` with `getent hosts`, that should help.
