### ISSUE TITLE
mini.json example missing dns configuration

### ISSUE THREAD

**Issue by claes** [dadevel/wg-netns#2]
I tried to run this using a customized version of the mini.json example (just with other keys etc). It failed with the following error message:

```
./wg-netns.py up ./mini.json
Cannot find device "wg-example"
error: subprocess failed: ip -n ns-example link set wg-example down: exit code 1 (RuntimeError)
```

I found that it was due to this line:
`content = '\n'.join(f'nameserver {server}' for server in namespace['dns-server'])`

When I added a valid dns server line to my json

```
  "name": "ns-example",
  "dns-server": ["8.8.8.8", "8.8.4.4"],
  "interfaces": [
```

It worked. Is it suppose to work without dns-server configured?

**Comment by dadevel** [comment]
> Is it suppose to work without dns-server configured?

Yes, it should have. Now it falls back to the servers configured in `/etc/resolv.conf`.

**Comment by claes** [comment]
Great. I must say this is an excellent tool

**Comment by dadevel** [comment]
Thanks. Nice to hear.
