### ISSUE TITLE
Hardened unit breaks due to mount namespacing

### ISSUE THREAD

**Issue by JeWe37** [dadevel/wg-netns#20]
a4c991a499b01c52f024c1895103dd6c04dbce33 hardened the systemd service unit, this however is causing issues, as the options:
```
ReadOnlyPaths=%E/wireguard
ReadWritePaths=%E/netns
PrivateDevices=true
PrivateMounts=true
PrivateTmp=true
ProcSubset=pid
ProtectControlGroups=true
ProtectHome=true
ProtectKernelLogs=true
ProtectKernelModules=true
ProtectKernelTunables=true
ProtectProc=noaccess
ProtectSystem=strict
```
All cause the creation of a mount namespace. This means that the mounts created in `/var/netns` by `ip netns` will not propagate to the main mount namespace, thereby making it impossible to execute a process in the namespace. I had to remove them in order to make the service work.

**Comment by dadevel** [comment]
Thanks for letting me know.
