### ISSUE TITLE
Put interfaces in main namespace

### ISSUE THREAD

**Issue by UpYoursMicrosoft** [dadevel/wg-netns#23]
Is it possible to to make wg-netns put the interfaces in the main namespace? Or, rather, outside of all the namespaces. I want to isolate my physical network interfaces in their own namespace and leave only Wireguard interfaces outside of it. I've tried a few different things in my config and I couldn't get it to work.

**Comment by dadevel** [comment]
That use case is currently not supported, but feel free to open a PR.
