### ISSUE TITLE
Running Firefox in the network namespace doesn't recover from network outages

### ISSUE THREAD

**Issue by ZornsLemma** [dadevel/wg-netns#25]
Thanks very much for wg-netns - I am using it on two machines to help share my VPN connection.

I love the trick of running Firefox in the network namespace and in general it works well. But I've noticed that if my network connection goes down and comes back up (because it's crap and it just does that sometimes, or because the machine has been suspended and resumed), the Firefox running in the network namespace seems to permanently lose network access. The wireguard connection inside the network namespace seems fine when this happens - I can "exec" into the namespace and ping things, and other processes on my machine using the wireguard connection work fine. It's just the Firefox in the network namespace that doesn't recover.

On a possibly related note, I also tried running Mullvad Browser in the network namespace and couldn't get it to work at all.

Do you have any idea what might be going on or how this can be fixed? It's not the end of the world but it's a bit annoying to have to restart that Firefox after every network outage.

**Comment by dadevel** [comment]
Sorry, but I don't know what cloud cause this behavior.

**Comment by ZornsLemma** [comment]
Thanks for getting back to me anyway, it's appreciated.

I am convinced there is a genuine issue here (albeit probably not one with wg-netns - I just hoped you might have some idea), but for what it's worth my machine suspended for an hour or so earlier today without the network namespace Firefox experiencing any problems. So the triggering event is probably not quite as simple as I described it above.

**Comment by dadevel** [comment]
Good luck getting to the bottom of this :)
