### ISSUE TITLE
Sudo based commands fail due to -D on stock Arch

### ISSUE THREAD

**Issue by regalialong** [dadevel/wg-netns#27]
When calling `wg-netns switch <ns>` installed through pipx, it errors with `sudo: you are not permitted to use the -D option with /usr/bin/bash`. Same with exec.

I believe breaking change happened [here](https://www.sudo.ws/repos/sudo/rev/d32e07966e0e), but I'm not too knowledgeable to help beyond that.
Sudoers need have `runcwd=*` to allow changing the working directory according to [this](https://www.sudo.ws/posts/2020/09/using-chroot-and-cwd-in-sudo/#changing-the-working-directory).

When removing `'-D', Path.cwd().as_posix()` from [the related action lines](https://github.com/dadevel/wg-netns/blob/121288feb936041149287456af23b6f741f56d76/wgnetns/main.py#L102-L105), this works but I'm not sure if this causes problems.

**Comment by dadevel** [comment]
Yes, I know the problem, but I'm not sure what to do about it.
Maybe remove any use of sudo and expect the user to run `sudo wg-netns` instead?
In the meantime `runcwd=*` works.

**Comment by regalialong** [comment]
Not sure how the situation is for other methods but my pipx copy without `-D` keeps me in the same directory.

**Comment by dadevel** [comment]
Oh, ok. I just removed the option.
